### PR TITLE
gix-fetchhead

### PR DESCRIPTION
**Pull request by Cyphecx**
Hello @Byron! Im getting started on the gix-fetchhead crate. I think I found the right types for the Struct members. 
Next I think I just need a parse function for the type that will read in from the FETCH_HEAD file.
Let me know if Im missing anything!

### CODE REVIEW

**Comment by Byron** [comment]
The `FETCH_HEAD` allows multiple lines, and there might be other details that are more obvious when looking at [its source code](https://github.com/git/git/blob/6807fcfedab84bc8cd0fbf721bc13c4e68cda9ae/builtin/fetch.c#L1055).

Further, I recommend taking a look at how tests are setup in this project, `gix-pathspec` should be a good example, which will allow you to setup your own FETCH_HEAD related tests.

Of course it's also possible to salvage a couple of representative FETCH_HEAD files from the wild and store them as fixtures.

**Comment by Byron** [comment]
I recommend running `just test` locally to see future CI failures early, and to keep CI green as well. Pushing code that doesn't build can most easily be avoided, but running linters is probably a more typical failure mode that `just test` helps to avoid.

**Comment by Cyphecx** [comment]
My apologies. I wanted the changes I was making to be visible but I didnt think of CI as I considered it a WIP. Ill make sure its in a good state before pushing now.

Also Im sorry about my slow progress. Most of my time is going towards wrapping my head around the codebase and the git source code.

**Comment by Byron** [comment]
> My apologies. I wanted the changes I was making to be visible but I didnt think of CI as I considered it a WIP. Ill make sure its in a good state before pushing now.

No worries! Please ignore the errors you see currently, there is a new Rust version (with impeccable timing) which causes breakage. You can rebase onto `main` soon to inherit the fixes.

> Also Im sorry about my slow progress. Most of my time is going towards wrapping my head around the codebase and the git source code.

I recommend gathering a couple of typical `FETCH_HEAD`s from the wild, and trying to parse them as part of a test. From there you can also validate round-tripping. The only code that should be of interest for this starts [about here](https://github.com/git/git/blob/d0e8084c65cbf949038ae4cc344ac2c2efd77415/builtin/fetch.c#L1039) - maybe focussing your efforts helps as well.

**Comment by Byron** [comment]
This branch can now be rebased onto `main` to fix CI.

**Comment by Cyphecx** [comment]
> Please ignore the errors you see currently, there is a new Rust version (with impeccable timing) which causes breakage.

Lol I may have spent a little bit trying to see if I caused it somehow.

Working on the parsing now, but I'm having an issue with the working directory in the test environment. Its seems to change the base directory almost at random? I think I am missing something since I haven't been able to find another test opening files in this manner.
```rust
//let path = gix_testtools::fixture_path("git");
//let path = gix_testtools::fixture_path_standalone("git");
let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
path.push("tests/fixtures/git");
println!("{path:?}");
```
When running `cargo test -all`, the path seems to become:

> "/home/wyatt/Documents/gitoxide/gix-fetchhead/tests/tests/fixtures/git"

but with `path.push("fixtures/git");` I get: 
> "/home/wyatt/Documents/gitoxide/gix-fetchhead/fixtures/git"

Im able to run the test directly with `cargo test` in the module directory, but Im not really sure how to make this work properly with the testing system. I tried out `gix_testtools::fixture_path` and `gix_testtools::fixture_path_standalone` but they seem to have the same issue.

**Comment by Byron** [comment]
That's strange as all crates use these functions. `gix_testtools::fixture_path()` (you can also just copy the code) seems to be the way to go with this and it works consistently. A test binary will always `chdir` into the same spot, and run all tests from there.

I hope that helps.

**Comment by Byron** [comment]
My recommendation for this PR is to close it and instead create a PR against your own fork (CI can be enabled there). This way you can come back once there is something to review.
Thank you.

**Comment by Cyphecx** [comment]
Will do. Sorry all the issues

**Pull request closed without merging**
