### PR TITLE
feat(git-date): Adds fuzzer for date parser

### PR DESCRIPTION
**Pull request by silvergasp**
This fuzzer almost immediately crashes the parser.
----

Ok for [Byron](https://github.com/Byron) review the PR on video?

- [x] I give my permission to record review and upload on YouTube publicly

If I think the review will be helpful for the community, then I might record and publish a video.

### CODE REVIEW

**Comment by Byron** [comment]
We have to be careful with this as there is limited control over the quality of the parser. Most of it is implemented in the `time` crate, which is also where the first immediate crash is happening.

Can we avoid throwing this into `OSS-FUZZ` while it's clear there will be a lot of crashes, most of which are outside of our control?

**Comment by Byron** [comment]
In any case, no way to hide, let's bring it in and deal with the fallout, maybe some crashes can be triggered within `gitoxide` itself, and from there we can see if fuzzing can be extended to `time` as needed.

**Comment by Byron** [comment]
@silvergasp Unrelated to this PR, I just got informed that [the builds on OSS-FUZZ](https://oss-fuzz-build-logs.storage.googleapis.com/log-4b532f9e-3180-473c-a4be-d9e6017f3ba7.txt) fail continuously. I don't know if this was a temporary failure, or what to do about it. Apparently the coverage report (python script) is failing as it can't find source code files of the standard library.

**Comment by silvergasp** [comment]
Hmm, I imagine we need to add the rust-src component using rustup.

`rustup component add rust-src`

I'm not sure if that needs to be in the dockerfile or in build.sh

I'll investigate tomorrow.

**Comment by silvergasp** [comment]
It doesn't look like the build is failing. There is a post-processing stage after collecting code coverage that looks like it's failing. That stage, in particular, will need the original source code that made the binary. But if the rust-src component isn't installed then it won't be able to produce a code coverage report. By default rust is going to use a precompiled std library.

**Comment by Byron** [comment]
Seems fair. What surprised me is that this happened now, and not immediately after setting up the fuzzing.

**Comment by silvergasp** [comment]
> Seems fair, thanks for the analysis. What surprised me is that this happened now, and not immediately after setting up the fuzzing.

Yeah, I think code-coverage is calculated every other day or so. So the builds are working fine, so there were no immediate red flags there. Although I'm surprised this wasn't caught in the Pull Request CI for oss-fuzz.

**Comment by silvergasp** [comment]
Moved this conversation to #719 as it doesn't seem to be related to this PR. I've also added a potential fix for this problem here https://github.com/google/oss-fuzz/pull/9581/

**Pull request merged**
