### PR TITLE
Move to the smaller, cargo-team maintained `home` crate

### PR DESCRIPTION
**Pull request by utkarshgupta137**
----

Ok for [Byron](https://github.com/Byron) review the PR on video?

- [x] I give my permission to record review and upload on YouTube publicly

If I think the review will be helpful for the community, then I might record and publish a video.

### CODE REVIEW

**Comment by Byron** [comment]
That's awesome, thanks a lot!

I wonder if [this implementation in `gitoxide`](https://github.com/Byron/gitoxide/blob/5d2b5d02c3869e07dc2507a8f2519ee1df633df7/gix-path/src/env/mod.rs#L103-L125) would also be suitable to not even have to use the `home`. It seems that `home` uses the winapi which should make it more resilient, but then again, it seems that [the respective `git` implementation](https://github.com/git/git/blob/7580f92ffa970b9484ac214f7b53cec5e26ca4bc/compat/mingw.c#L2714) is worse than even the one of `gix-path` which handles more special cases.

So I am thinking that `home` can be removed entirely in favor of `gix-path`. What do you think?

**Comment by utkarshgupta137** [comment]
Well, the [`home_dir`](https://doc.rust-lang.org/std/env/fn.home_dir.html) function in std was deprecated for using `HOME` on Windows. The git implementation you linked to seems to be only used under MinGW? In that case, it would be fine. If this crate is supposed to work outside MinGW/Cygwin, then I think it would be better to update gix-path too to use the `home` crate.

**Comment by Byron** [comment]
That's a very valid point - I tend to make the mistake of looking at this minGW code and thinking it's for all of windows, even if it's still 'just' a compatibility layer of sorts which doesn't exist for applications using `gitoxide`.

Thus I agree, and will be using `home` in `gix-path` accordingly.

**Comment by Byron** [comment]
I had to revert the change to `gix-path` as it is used in the WASM builds. Apparently [`home` doesn't yet build there](https://github.com/Byron/gitoxide/actions/runs/4772443930/jobs/8484956259). `gix-sec` seems to not be used there, as right now only a few crates are validated to work in this environment.

**Comment by utkarshgupta137** [comment]
> I had to revert the change to `gix-path` as it is used in the WASM builds. Apparently [`home` doesn't yet build there](https://github.com/Byron/gitoxide/actions/runs/4772443930/jobs/8484956259). `gix-sec` seems to not be used there, as right now only a few crates are validated to work in this environment.

You could use the `HOME` variable for wasm targets & `home_dir` for everything else?

**Comment by Byron** [comment]
Could you open a new PR and make it work there? Maybe it's as easy as using `home` on windows and asking for `HOME` everywhere else.

I am also investigating a failure in my current PR which seems to be due to `home` even though it shouldn't be used there, very puzzling.

**Comment by utkarshgupta137** [comment]
> Could you open a new PR and make it work there? Maybe it's as easy as using `home` on windows and asking for `HOME` everywhere else.
> 
> I am also investigating a failure in my current PR which seems to be due to `home` even though it shouldn't be used there, very puzzling.

Created #826

**Pull request merged**
