### PR TITLE
Add commit signature extraction

### PR DESCRIPTION
**Pull request by Jake-Shadle**
This PR adds the equivalent of libgit2's [`commit_extract_signature`](https://libgit2.org/libgit2/#HEAD/group/commit/git_commit_extract_signature) to Commit/Ref as I encountered a [use case](https://github.com/rustsec/rustsec/blob/76d509d014b1b0c7206f0df4e953b3b59ab4b286/rustsec/src/repository/git/commit.rs#L63) for it while porting some code from git2.

The API is admittedly wonky so let me know if you want changes.

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot! I am taking a look now, and plan to merge the refactored version of it.

**Comment by Jake-Shadle** [comment]
Oh yeah, that might be the case, that's unfortunate.

**Comment by Byron** [comment]
I am closing this PR as it has been superseded by the refactored version (see #973). You can now try validation yourself using `gix commit verify` - it's just a quick MVP to be able to see if `SignedData` is actually what we think it should be. I was lucky enough to remove all the special cases and whitespace logic early and what ended up being there just worked 🙏.

Further, please feel free to ping me when you need a new release.

**Comment by Jake-Shadle** [comment]
Much better, thanks.

**Pull request closed without merging**
