### PR TITLE
Speedup ci

### PR DESCRIPTION
**Pull request by NobodyXu**
- Run doc-test in test-fast
 - Use cargo-nextest for job test
 - Do not remove `target`

### CODE REVIEW

**Comment by NobodyXu** [comment]
@Byron it shows that this PR makes ci.yml 5m faster

**Review by Byron — APPROVED** [review]
This is a very impressive outcome, thanks so much!

I am also surprised that `cargo nextest` manages to do the same faster, but maybe it's just the removal of `clear-target` (which exists there for reasons lost to time) which so much.

In any case, I prefer the output of `cargo nextest` and wasn't aware it can be used as `cargo test` stand-in - it's very neat, indeed!

**Comment by NobodyXu** [comment]
> I am also surprised that cargo nextest manages to do the same faster, but maybe it's just the removal of clear-target 

It could be caching, but nextest is indeed faster if you have lots of tests and more than 1 cores, I checked the log it does run tests for some crates faster by running them in parallel by spawning one process for each tests.

It might be more robust if your tests involve global variables or potential UBs, running in separate processes protects against that.

**Comment by NobodyXu** [comment]
> wasn't aware it can be used as cargo test stand-in - it's very neat, indeed!

It's not a full drop-in, it can't run doc-test right now, you'd need `cargo test --doc`.

However I think you don't have the habit of using doc-test so often as most of the valuable tests is probably in `tests/` or under `#[cfg(test)] mod tests`

**Comment by NobodyXu** [comment]
P.S. nextest also integrates with llvm-cov, miri, criterion and cargo-mutants

https://nexte.st/docs/integrations/

**Comment by NobodyXu** [comment]
https://github.com/nextest-rs/reuse-build-partition-example/blob/main/.github/workflows/ci.yml

And it can:
 - compile the tests and run it on different machines
 - partition the tests, run tests in parallel on different machines/GHA runners

**Comment by Byron** [comment]
Thanks again for the heads-up!
`cargo nextest` is truly fascinating, and I hope that one day it will also learn how to run `doc` tests (even though it now also improves to be more efficient when compiling and running these tests).

**Pull request merged**
