### PR TITLE
Bump dep reqwest from 0.11.12 to 0.12.0

### PR DESCRIPTION
**Pull request by NobodyXu**
reqwest 0.12.0 has released, which finally switched to hyper v1

https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0

### CODE REVIEW

**Comment by Byron** [comment]
That seemed…easier than I thought it would be, awesome!

I will merge once CI is green and *believe* this isn't a breaking change as the `request` API doesn't leak into the public surface of any crate.

**Comment by NobodyXu** [comment]
Thanks!

I would never know how to fix the tests by myself 😂

**Comment by NobodyXu** [comment]
@Byron Can we publish a new patch release please?

**Comment by Byron** [comment]
Alright, `gix` 61.1 was released, which goes hand in hand with the `gix-transport` crate which was adjusted here.

**Comment by NobodyXu** [comment]
Thanks!

**Pull request merged**
