### PR TITLE
Copy over code from gix to generate completions for ein as well

### PR DESCRIPTION
**Pull request by sbatial**
One thing to note: It currently takes `gitoxide` instead of `ein` as the command.
I don't know why it does that.
The command name is taken from Args, and using the locally build version of gix does not do that (I figured it might be an issue with the manual build).

I'll try to investigate but I'd be glad about any hints.

If nothing comes up it would always be possible to just hardcode the name of the binary until the culprit is found.

### CODE REVIEW

**Comment by Skgland** [comment]
> One thing to note: It currently takes `gitoxide` instead of `ein` as the command. I don't know why it does that. The command name is taken from Args, and using the locally build version of gix does not do that (I figured it might be an issue with the manual build).

`app.get_name()` appears to default to the default to the package name, adding a `#[command(name = "gix")]` to the definition of `App` might help, [`clap docs`](https://docs.rs/clap/latest/clap/_derive/_cookbook/git_derive/index.html)

**Comment by sbatial** [comment]
@Skgland thanks! that should do the trick.

I tried to find where gix and ein differ in implementation but didn't spot that Args does indeed have a name set.

**Comment by sbatial** [comment]
Not sure if I should add you as a co-author/how to do that properly, but at least according to my local build that did the trick!

**Review by Byron — APPROVED** [review]
Thanks a lot - a great addition!

**Pull request merged**
