### PR TITLE
clippy: activate `clippy::enum-glob-use`

### PR DESCRIPTION
**Pull request by poliorcetics**
Helps with #874

### CODE REVIEW

**Comment by poliorcetics** [comment]
I ran `just fmt` locally and it changed lots of imports, was that expected ?

**Comment by poliorcetics** [comment]
The job `cargo-deny (bans licenses sources)` failing seems unrelated ? I added no deps nor changed any

**Comment by Byron** [comment]
That should indeed be unrelated, I will see to fix it in `main` if it persists.

> I ran `just fmt` locally and it changed lots of imports, was that expected ?

Yes, as I run it only rarely and usually forget. Ideally it's run after each work-block, and last time I forgot.

Besides that, thanks a lot for tackling this, it's appreciated even though I have to postpone the review as I am still recovering from COVID. I'd hope I have the focus for that within a a couple of days though.

**Comment by Byron** [comment]
I am sorry, but have to reject this one, as I am not a fan of not being allowed to use function-private enum-globs. They actually make the code more readable which becomes obvious now that I see it.

Secondly, `just fmt` shouldn't be mixed in which seems to be the case here - this is merely for future reference.

Thanks for your understanding.

**Pull request closed without merging**
