### PR TITLE
write blob

### PR DESCRIPTION
**Pull request by ultrasaurus**
expand `init-repo-and-commit.rs` to write another commit a blob

It doesn't write a file to the local filesystem, just the commit.  I honestly didn't know how it was going to work before I wrote the code.  Then I thought this might be the way one might use git as data storage from an application where the user interacts with the app not the filesystem (and, if that's a valid use case, might change so it saves data that is less file-like).

interested in feedback!

----

Can [Byron](https://github.com/Byron) review the PR on video?

Please choose one - no choice means no recordings are made.

- [x] Record if you want to

### CODE REVIEW

**Comment by ultrasaurus** [comment]
I took some time out and learned about bare repositories.  I wonder if this example should be with a bare repository so it makes sense to not update local file system?

**Comment by Byron** [comment]
Thanks a lot, much appreciated!

> I took some time out and learned about bare repositories. I wonder if this example should be with a bare repository so it makes sense to not update local file system?

Indeed, at this point it's a bare repository and all objects are created entirely without the help of a work-tree, and I made the necessary modifications. Maybe the example could be renamed as well but it's not paramount just yet.

I also added a missing methods to avoid having to user lower level methods on `repo.objects` - there is nothing wrong with that, but I think typical workflows should be supported by `Repository` itself.

In time there can be another version of this that uses a worktree, and it will look entirely differently as it's more akin to what a user would do, i.e. write files to disk, add them to the index and committing that with the tree being auto-generated from it.

**Review by Byron — APPROVED** [review]
Looks good to me already.

**Comment by ultrasaurus** [comment]
looks great. thanks!

**Pull request merged**
